<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>Imports</string>
	</array>
	<key>name</key>
	<string>Imports</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#empty</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#path</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>^\/\/.*$</string>
			<key>name</key>
			<string>comment.imports</string>
		</dict>
		<key>empty</key>
		<dict>
			<key>match</key>
			<string>^\s*$</string>
			<key>name</key>
			<string>empty.imports</string>
		</dict>
		<key>imports</key>
		<dict>
			<key>match</key>
			<string>\.imports</string>
			<key>name</key>
			<string>constant.language.imports</string>
		</dict>
		<key>js</key>
		<dict>
			<key>match</key>
			<string>\.js</string>
			<key>name</key>
			<string>keyword.imports</string>
		</dict>
		<key>json</key>
		<dict>
			<key>match</key>
			<string>\.json</string>
			<key>name</key>
			<string>entity.other.attribute-name.imports</string>
		</dict>
		<key>path</key>
		<dict>
			<key>begin</key>
			<string>^</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>string.imports</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#var</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#imports</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#json</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#js</string>
				</dict>
			</array>
		</dict>
		<key>var</key>
		<dict>
			<key>match</key>
			<string>\$[a-zA-Z0-9]*</string>
			<key>name</key>
			<string>support.type.variable.imports</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.imports</string>
	<key>uuid</key>
	<string>3d8cd709-474c-4bfe-9cdf-986f5d86a0b0</string>
</dict>
</plist>
